## NumPy

NumPy (Numerical Python) é uma bilbioteca do Python que é utilizada para processamentos numéricos.
Normalmente o pessoal utiliza a abreviação np quando chama a biblioteca para ficar mais fácil de trabalhar com ela,
como segue o exemplo:

**import numpy as np**

#### Algumas aplicações que podem ser utilizadas com o NumPy:

- Operações rápidas em arrays, limpeza de dados, geração de subconjuntos e filtragens, transformações e outros tipos de processamentos 
- estatísticas descritivas e agregações/sintetização dos dados;
- expressões lógicas.

##### Na maioria das vezes você terá associado ao NumPy a infomação ndarray que é um objeto N-dimensional par um grande conjunto de dados

In [1]:
#exemplos
import numpy as np
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
#gerando dados aleatorios
np.random.randn(2,3)
#randn gera valores aleatorios normais entre 0 e 1

array([[ 0.43396952, -0.39270005,  2.04932853],
       [ 0.44264216, -0.72798007, -2.20425602]])

In [3]:
#convertando uma lista para array e verificando suas informações
df = [1,2,3,4,5,6.8,11.5]
arr = np.array(df)
arr


array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6.8, 11.5])

In [4]:
#é possível criar sequencias aninhadas também
import numpy as np
df2 = [[1,2,3,4], [5,6,7,8,9]]
arr2 = np.array(df2)
arr2

array([list([1, 2, 3, 4]), list([5, 6, 7, 8, 9])], dtype=object)

In [5]:
arr2.ndim

1

In [6]:
arr2.shape

(2,)

In [7]:
arr.dtype

dtype('float64')

#### Temos também outros formatos para criar arrays

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
#np.empty() nem sempre devolverá array somente com zeros.
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
#Arange é uma faunção similar range
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
#Na hora de criar um array você pode especificar qual o tipo de dado você quer
import numpy as np
arr3 = np.array([1,2,3], dtype = np.float64)
arr4 = np.array([1,2,3], dtype = np.int32)

In [18]:
arr3.dtype

dtype('int32')

In [17]:
arr4.dtype

dtype('int32')

In [20]:
#Podemos usar o astype também
arr5 = np.array([1,2,3,4,5])
arr5.dtype

dtype('int32')

In [22]:
arr5 = arr4.astype(np.float64)
arr5.dtype

dtype('float64')

In [25]:
#Artimética com array
arr3+arr3

array([2., 4., 6.])

In [26]:
arr3 * arr4

array([1., 4., 9.])

In [31]:
#Se quiser copiar parte de array você pode utilizar a função copy
import numpy as np
arr10 = ([0,1,2,3,4,5,6,7,8,9,10])

In [32]:
arr11 = arr10[5:8].copy()
arr11

[5, 6, 7]

In [35]:
#Selecionar um valor especifico em arrays multidimensional
import numpy as np
arrmult = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

In [36]:
#retorna o valor da segunda lista na posição 3
arrmult[1][3]

9

In [55]:
#retorna a primeira lista
arrmult[:1, :]

array([[1, 2, 3, 4, 5]])

In [57]:
#retonar a primeira coluna
arrmult[:, :1]

array([[ 1],
       [ 6],
       [11]])

In [58]:
#retona até a segunda lista e a primeira coluna
arrmult[:2,:1]

array([[1],
       [6]])

### A expressão ***where*** funciona como uma condição lógica para operações com array

In [60]:
import numpy as np
arr = np.random.randn(4,4)
arr

array([[ 1.12983614,  0.33219324,  0.87319925, -0.92668604],
       [ 0.57273601,  0.16835168,  1.10199982,  0.20684094],
       [ 1.15534562,  1.20482186,  2.20474508, -0.33642174],
       [-0.01523015, -0.59679154,  0.89552492, -0.19476422]])

In [61]:
arr > 0

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False,  True, False]])

In [62]:
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2, -2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2, -2],
       [-2, -2,  2, -2]])

### Operações matemáticas e estatísticas com NumPy


In [3]:
import numpy as np
df = np.random.randn(4,4)
df

array([[-0.92999513,  0.10087061,  0.15109025, -0.01883136],
       [ 0.08384165,  1.45844416,  0.5828748 ,  0.51975881],
       [-0.67106061,  1.20752547, -0.68282725, -0.66028858],
       [-0.33855851,  0.04545186,  0.43284679,  0.66405671]])

In [4]:
# mean
df.mean()

0.12157497958209798

In [6]:
np.mean(df)

0.12157497958209798

In [7]:
# sum
df.sum()

1.9451996733135677

In [8]:
np.sum(df)

1.9451996733135677

#### **Mean** and **Sum** aceitam axis para calculos em linhas e colunas. axis = 0 calcula linha e axis = 1 calcula coluna

In [9]:
df.mean(axis =1)

array([-0.17421641,  0.66122985, -0.20166274,  0.20094921])

In [10]:
df.sum(axis = 0)

array([-1.8557726 ,  2.8122921 ,  0.48398459,  0.50469559])

#### Outras funções que são uteis:
- std = desvio padrão
- var = variancia
- min = mínimo
- max = máximo
- argmin = índices dos elementos mínimo
- argmax = índices dos elementos máximo
- cumsum = soma cumulativa dos elemento, começando de 0
- cumprod = produtivo cumalativo dos elementos, começando de 1

## Ordenação

In [3]:
import numpy as np
df = np.random.randn(6)
df

array([ 1.11464096,  0.19811493,  0.36443332,  0.26565975, -0.51341367,
       -1.05228722])

In [4]:
df.sort()
df

array([-1.05228722, -0.51341367,  0.19811493,  0.26565975,  0.36443332,
        1.11464096])

### Lista com alguns comandos
- unique(x) = Calcula os elementos únicos ordenados
- intersect1d(x, y) = Calcula os elementos comuns ordenados em x e y
- union1d(x, y) = Calcula a união ordenada dos elementos
- in1d(x, y) = Calcula um array booleano indicando se cada elemento em x está contido em y
- setdiff1d(x, y) = Diferença entre os conjuntos, isto é, elementos em x que não estão em y
- setxord1f(x, y) = Diferença simétrica entre conjuntos: elementos que estão em apenas um dos arrays, mas não em ambos

## Algumas funções de Algebra Linear
- diag = Devolve os elementos (ou fora da diagonal) de uma matriz quadrada como um array 1D, ou converte um array 1D em uma matriz quadrada, com zeros fora da diagonal
- dot = Multiplicação de matrizes
- trace = Calcula a soma dos elementos da diagonal
- det = Calcula o determinante da matriz
- eig = Calcula os autovalores (valores próprios) e os autovetores de uma amtriz quadrada
- inv = Calcula a inversa de uma matriz quadrada
- pinv = Calcula a pseudoinversa de Moore-Penrose de uma matriz
- qr = Calcula a decomposição QR
- svd = Calcula SVD (Decomposição de Valor Singular)
- solve = Resolve o sistema linear Ax = b para x, em que A é uma matriz quadrada
- lstsq = Calcula a solução de quadrados mínimos para Ax = b